### ISSUE TITLE
Launching tasks/composed-tasks fails with an error

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#734]
As a user, I'm attempting to launch a composed task from the UI, but it fails with the following error in the backend. Launches work fine from the Shell, though.

Launch:
![image](https://user-images.githubusercontent.com/1562654/38961555-e8219fca-431d-11e8-9c38-f77177e2e78e.png)

Error:
```
2018-04-18 15:31:36.102 ERROR 57589 --- [io-9393-exec-10] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request

java.lang.IllegalArgumentException: The provided taskName must not be null or empty.
	at org.springframework.util.Assert.hasText(Assert.java:181) ~[spring-core-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskService.executeTask(DefaultTaskService.java:168) ~[spring-cloud-dataflow-server-core-1.5.0.M1.jar!/:1.5.0.M1]
```

**Comment by sabbyanandan** [comment]
Same error for regular task launches, too.
