### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by windonTest** [spring-cloud/spring-cloud-dataflow-ui#885]
dashboard project is imported eclipse,How to compile jar packets？
Mine always report mistakes.

for example：

```0 info it worked if it ends with ok
1 verbose cli [ 'G:\\spring_cloud\\new_0903\\spring-cloud-dataflow-ui\\ui\\node\\node.exe',
1 verbose cli   'G:\\spring_cloud\\new_0903\\spring-cloud-dataflow-ui\\ui\\node\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'mavenbuild-without-tests' ]
2 info using npm@6.2.0
3 info using node@v10.8.0
4 verbose run-script [ 'premavenbuild-without-tests',
4 verbose run-script   'mavenbuild-without-tests',
4 verbose run-script   'postmavenbuild-without-tests' ]
5 info lifecycle spring-cloud-dataflow-ui@1.3.0~premavenbuild-without-tests: spring-cloud-dataflow-ui@1.3.0
6 info lifecycle spring-cloud-dataflow-ui@1.3.0~mavenbuild-without-tests: spring-cloud-dataflow-ui@1.3.0
7 verbose lifecycle spring-cloud-dataflow-ui@1.3.0~mavenbuild-without-tests: unsafe-perm in lifecycle true
8 verbose lifecycle spring-cloud-dataflow-ui@1.3.0~mavenbuild-without-tests: PATH: G:\spring_cloud\new_0903\spring-cloud-dataflow-ui\ui\node\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;G:\spring_cloud\new_0903\spring-cloud-dataflow-ui\ui\node_modules\.bin;G:\spring_cloud\new_0903\spring-cloud-dataflow-ui\ui\node;C:\ProgramData\Oracle\Java\javapath;G:\jdk1.7_64\jdk1.7.0_40\bin;D:\var\windon\hadoop-2.6.5\bin;C:\Program Files (x86)\Common Files\NetSarang;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Python27;G:\maven\apache-maven-3.2.5\bin;H:\program\svn_p\bin;D:\program\Git\bin;D:\program\Git\cmd;
9 verbose lifecycle spring-cloud-dataflow-ui@1.3.0~mavenbuild-without-tests: CWD: G:\spring_cloud\new_0903\spring-cloud-dataflow-ui\ui
10 silly lifecycle spring-cloud-dataflow-ui@1.3.0~mavenbuild-without-tests: Args: [ '/d /s /c',
10 silly lifecycle   'node ./node_modules/@angular/cli/bin/ng build --prod --output-path ./../target/classes/public/dashboard --base-href /dashboard/' ]
11 silly lifecycle spring-cloud-dataflow-ui@1.3.0~mavenbuild-without-tests: Returned: code: 1  signal: null
12 info lifecycle spring-cloud-dataflow-ui@1.3.0~mavenbuild-without-tests: Failed to exec mavenbuild-without-tests script
13 verbose stack Error: spring-cloud-dataflow-ui@1.3.0 mavenbuild-without-tests: `node ./node_modules/@angular/cli/bin/ng build --prod --output-path ./../target/classes/public/dashboard --base-href /dashboard/`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (G:\spring_cloud\new_0903\spring-cloud-dataflow-ui\ui\node\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (G:\spring_cloud\new_0903\spring-cloud-dataflow-ui\ui\node\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:249:5)
14 verbose pkgid spring-cloud-dataflow-ui@1.3.0
15 verbose cwd G:\spring_cloud\new_0903\spring-cloud-dataflow-ui\ui
16 verbose Windows_NT 6.1.7601
17 verbose argv "G:\\spring_cloud\\new_0903\\spring-cloud-dataflow-ui\\ui\\node\\node.exe" "G:\\spring_cloud\\new_0903\\spring-cloud-dataflow-ui\\ui\\node\\node_modules\\npm\\bin\\npm-cli.js" "run" "mavenbuild-without-tests"
18 verbose node v10.8.0
19 verbose npm  v6.2.0
20 error code ELIFECYCLE
21 error errno 1
22 error spring-cloud-dataflow-ui@1.3.0 mavenbuild-without-tests: `node ./node_modules/@angular/cli/bin/ng build --prod --output-path ./../target/classes/public/dashboard --base-href /dashboard/`
22 error Exit status 1
23 error Failed at the spring-cloud-dataflow-ui@1.3.0 mavenbuild-without-tests script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by windonTest** [comment]
What environment does it need to function properly?

**Comment by sabbyanandan** [comment]
Hi, @windonTest. How are you building the project? We typically build the project via terminal with the latest version of npm/node in the path. Also, we deliver the `jar` artifact of the UI project via Spring Repos and Maven Central. Is there a particular requirement to why you're building the project locally?

If you can describe the steps, we would be able to have a look.

**Comment by windonTest** [comment]
Thank you. 
Because I want to make the UI interface Chinese locally. Some dependencies cannot be downloaded locally, errors are reported all the time
It's all right now.After correcting the version number of "rxjs-compat" in UI /package.json file

**Comment by sabbyanandan** [comment]
Thanks for the update! Since you were able to resolve the problem, I will close the issue. If you have any other questions, ping us at Gitter or StackOverflow.
